Repository xarray-contrib/xwrf, pull requests merged in 2022-01, with the labels that each got.

#30 Update pre-commit hooks
  .pre-commit-config.yaml
  docs/source/conf.py
  pyproject.toml
  setup.cfg
Labels: maintenance, CI

#27 Removed units attributes from bool arrays
  tests/sample-data/wrfout_d03_2018-10-18_00:00:00_only_attrs.nc
  tests/test_units_fixed.py
  xwrf/io_plugin.py
Labels: enhancement

#34 Fix for issue template
  .github/ISSUE_TEMPLATE/other.yml
Labels: bugfix
