Repository xarray-contrib/xwrf, pull requests merged in 2022-09, with the labels that each got.

#93 Add destaggering functionality
  .github/workflows/ci.yaml
  .github/workflows/upstream-dev-ci.yaml
  setup.py
  tests/test_accessors.py
  tests/test_destagger.py
  xwrf/accessors.py
  xwrf/destagger.py
Labels: enhancement

#101 Fix staggered coordinate destaggering for dataarray destagger method
  tests/test_accessors.py
  xwrf/accessors.py
Labels: bug, bugfix

#100 Added earth-relative wind field calculation to base diagnostics
  tests/test_postprocess.py
  xwrf/accessors.py
  xwrf/postprocess.py
Labels: enhancement

#103 Clean up _destag_variable with respect to types and terminology
  tests/test_destagger.py
  xwrf/destagger.py
Labels: maintenance

#106 Clear c_grid_axis_shift from attrs when destaggering
  tests/test_accessors.py
  xwrf/destagger.py
Labels: bug, bugfix

#89 Update of tutorials for v0.0.2
  ci/environment-docs.yml
  docs/source/tutorials/Overview.md
  docs/source/tutorials/metpy.md
  docs/source/tutorials/xgcm.md
Labels: documentation
